services:
  db:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'silverspin'
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
volumes:
  mysql_data:
    external: false